version: '3.7'

services:
    db:
        image: 'mongo'
        container_name: db
        hostname: mongo
        ports:
          - "27017:27017"
        networks:
          - main-network

    mongo-express:
        image: mongo-express
        ports:
          - "8081:8081"
        environment:
          ME_CONFIG_MONGODB_URL: "mongodb://rootuser:rootpass@mongo:27017/"
          ME_CONFIG_BASICAUTH_USERNAME: fragaessetempero
          ME_CONFIG_BASICAUTH_PASSWORD: "!@34QWer%Tufj8"
          ME_CONFIG_MONGODB_PORT: 27017
          ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
          ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
        depends_on:
          - db
        links:
          - db
        networks:
          - main-network
      
networks:
  main-network:
    driver: bridge